export const allProjects = [
    {   id:1,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:2,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:3,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:4,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:5,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:6,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:7,
        img:"https://i.ibb.co/mb9Xnq9/avatar-Title.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:8,
        img:"https://i.ibb.co/Nr8mb0Y/projectimg.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
    {
        id:9,
        img:"https://i.ibb.co/mb9Xnq9/avatar-Title.jpg",
        name:"Project1",
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    },
]